#!/bin/bash

set -e

echo "disabling and stopping the services..."
if [ -x /bin/systemctl ]; then
  systemctl stop x735-fan.service
  systemctl stop x735-pwr.service
  systemctl disable x735-fan.service
  systemctl disable x735-pwr.service
  systemctl daemon-reload
fi